README.md
Fixes #32.
We now link to the proper testnet aperture installation instead of the staging environment.
=> readme: fix link to demo

aperture.go
This prevents a panic on startup for instances running with configurations that don't specify any Tor options.
=> aperture: check tor config nil-ness before access

aperture.go, config.go, proxy/proxy.go, proxy/proxy_test.go, sample-conf.yaml
We don't want to serve static files by default.
=> config+proxy: disable static file serving by default

aperture.go
In this commit, we modify our cipher suites and required TLS versions to
allow anything greater than TL 1.1. TLS 1.0 (sslv3) is broken so we
require versions that're safely above that. Without this change, widely
used clients such as `openssl` will fail to connect out to an Aperture
proxy.
=> aperture: relax TLS requirements

aperture.go, challenger.go, challenger_test.go
Fixes the issue `Deny: Invoice status mismatch: no active or settled invoice found for hash=5e0...` when aperture loses its connection to lnd. For now we just shut down so an orchestrator can restart it when the connection is available again.
=> challenger: shutdown if connection to lnd is lost

.github/workflows/docker.yml, Dockerfile, aperture.go, go.mod, go.sum, internal/test/lightning_client_mock.go, internal/test/walletkit_mock.go
We update to `lnd v0.11.1-beta` and `lndclient v0.11.0-4` and add a new production `Dockerfile` and a GitHub workflow that is triggered whenever a new version tag is
pushed. It will trigger a docker image build for that version and automatically push it to the specified repo.
For this to work, the GitHub repository needs the following two secrets to be configured:
```
DOCKER_USERNAME: <the user to log into Docker Hub>
DOCKER_API_KEY: <an API key generated by Docker Hub for the above user>
```
=> maintenance: update lnd dependencies, prepare for production docker images

aperture.go, config.go, proxy/service.go
When starting to study how the code works I've just stumbled across a few instances of Kirin (which according to 0c14706fa4e8c4903e0b7d6ba79de3a5324c65b9 is the old name). Trivial search & replace (with sed) to move everything to Aperture. Hopefully after I get a better understanding of this I can contribute something more useful too.
=> Kirin comments renamed to Aperture

lsat/client_interceptor.go, lsat/client_interceptor_test.go, lsat/store.go, proxy/proxy_test.go
Related to https://github.com/lightninglabs/pool/issues/221.
This PR removes a pending LSAT if the payment for it is in a terminal failed state and tries a new payment. This removes the need for the user to manually remove the `lsat.token.pending` file from disk to try again.
=> Remove token if payment failed and try again

proxy/proxy.go, proxy/proxy_test.go
The last bugfix (#52) added some explicit header fields in an attempt of
fixing an issue with error responses. Unfortunately they weren't
strictly needed for the fix but ended up causing issues in a non-error
case.
This commit removes those header fields again and makes sure the "auth
header not found in response" header doesn't occur anymore.
=> proxy: remove manual trailer fields

aperture.go
Use the existing `servername` config parameter (also used with LetsEncrypt when `autocert = true`) as an extra domain to be added to self-signed certificates. This is useful for non-public endpoints, where autocert is not an option.
=> aperture: add servername to self-signed cert

aperture.go, config.go, go.mod
This PR updates aperture to allow specifying configuration options on the command line and adds an optional `configfile` flag to point to a custom location (rather than the default `aperture.yaml`).
This change relaxes our requirement that the default `aperture.yaml` exists, since we could have all of our options specified inline. It also tightens up the validation we require on our config to ensure that we start up with the minimum required config.
=> aperture: allow command line flags and add config file

aperture.go, config.go
This PR adds a base dir to aperture for move convenient file placement. 
There's always some thinking to so with our various file placement flags (specifically `--configfile` and `--basedir`), gone with the following logic: 
* Default to `AppDir` if nothing is set
* If only `--configfile` is set, use `AppDir` for files, use custom config location and require that it exists
* If only `--basedir` is set, look for `aperture.yaml` in `basedir` but do not require it
* If `--configfile` and `--basedir` are set, use `basedir` for files and require `--configfile` exists
Reason for allowing a `--configfile` and `--basedir` is that custom config file allows you to set the name of your config file as well as location.
=> multi: add base dir to aperture

aperture.go, config.go, go.mod, go.sum, hashmail_server.go, hashmail_server_test.go, proxy/proxy.go, proxy/proxy_test.go, sample-conf.yaml
Adds code for the mailbox server.
=> hashmailrpc: Add mailbox

config.go
Add group and namespace to hashmail config so that hashmail params can
be specified on the command line.
=> config: add group and namespace to hashmail config

aperture.go
Set the ping and pong intervals of the websocket proxy to zero in order
to disable them. This is needed since a browser client is unable to
respond to these pings.
Fixes https://github.com/lightninglabs/lightning-node-connect/issues/11
=> aperture: disable websocket proxy pings for hashmail server

aperture.go
Lower the MinTime frequency that the client is allowed to send pings to
1 min instead of the default of 5 mins.
=> aperture: hashmail keepalive enforcement policy

aperture.go, config.go, hashmail_server.go, prometheus.go, sample-conf.yaml
Extract prometheus config so that it can be used more generally & get metrics for number of active mailboxes
=> multi: mailbox metrics

hashmail_server.go, prometheus.go
In this commit, we add a mailbox-read-count metric. This will be
incremented each time a mailbox with an _odd_ stream ID is read from.
We do this because we assume that a full duplex connection is being used
meaning that there will be 2 streams that have a matching ID except for
the last byte. And so to avoid duplicating the data, we only record the
odd streams. We also assume that for every read, there will be a write
and so we only record the reads.
=> multi: add mailbox read counter

aperture.go, config.go, sample-conf.yaml
This commit adds a config option that can be set in order to spin up a
pprof profile server on the given port.
=> multi: profile server

aperture.go, config.go, hashmail_server.go, hashmail_server_test.go
In this commit, we start a timer if a mailbox stream is completely 
un-occupied (neither read or write stream is occupied). The timer 
is stopped if either of the streams are occupied and is reset if 
both streams are unoccupied. If the timer ever ticks then the 
mailbox stream is torn down. The default "stale time" is set to one 
hour but this can be set via the `hashmail.staletimeout` flag.
=> multi: gc stale mailboxes

.gitignore, aperture.go, lsat/satisfier.go, lsat/satisfier_test.go, lsat/service.go, mint/mint.go, mint/mint_test.go, mint/mock_test.go, proxy/service.go, sample-conf.yaml, services.go
This is a proof of concept to address #80. It is loosely inspired by `macaroontimeout` and [`TimeoutConstraint`](https://github.com/lightningnetwork/lnd/blob/28ea2736a04566b06c38533e5e48e1b8d185a49b/macaroons/constraints.go#L74-L81) in lnd. 
The way the api for this is supposed to work is that if you want your minted lsats to have an "expiration" for specific services, you set a timeout property in your aperture config at the service level (same as `capabilities` and `constraints`). This should be a value that equates to the number of seconds after minting that the lsat should expire. When the lsat is minted, this value will be consumed and the unix timestamp for that number of seconds from that moment will be added as the value for a caveat with the condition `[service_name]_timeout`. …
=> Timeout Caveat Support

challenger/lnd.go, config.go
In this PR, we fix to disticnt bugs:
1. AMP invoices dont' have a payment hash, so if you connect to a node that has one, then some belt-and-suspenders parsing will fail. 
2. For the yaml parser, since the public attribute differs from the name of the yaml field, we need to specify the `yaml` flag.
* Without this fix, the new backend can't be specified in the config file, only the command line args.
=> challenger+config: fix bugs related to config parsing and AMP invoice handling 

aperture.go
Make the LNC authenticator use the default mailbox address whenever the config does not specify a custom one.
=> config: set default mailbox address

.github/workflows/main.yml
Since the currently failing step of the sqlc check job is only a cache, it shouldn't cause the whole job to fail.
So we continue on error but also switch to a maintained fork of the cache action which should fix the error in the first place.
=> GitHub: update caching to maintained fork, continue on error

aperture.go, config.go
In this commit, we fix a subtle bug in the parsing of the yaml config. With the way the library works, the attribute name needs to match the config attribute name. Otherwise, parsing just doesn't work.
=> config: fix profile port arg parsing

sample-conf.yaml
- Change the passphrase placeholder.
- Group fields by category.
=> config: make `sample-conf.yaml` less error prone

auth/authenticator.go, auth/interface.go, auth/mock_authenticator.go, proxy/proxy.go, proxy/proxy_test.go
Fixes https://github.com/lightninglabs/aperture/issues/114.
=> proxy+auth: fix post request

l402/identifier.go, l402/identifier_test.go
If a TokenID is passed by value to logging functions (such as the Printf family) the pointer-based String() method is not used. As a result, the token is logged as an array when using %v and as binary when using %s, which is inconvenient.
=> l402: make TokenID.String() a value method

proxy/proxy.go, proxy/proxy_test.go, proxy/service.go, sample-conf.yaml
This PR adds a new list for the config which will allow skipping the creation of invoices on these specific calls.
This is useful for streaming rpcs, as we can't handle the l402 handshake there (yet?).
=> Add Invoice skip list

aperture.go, challenger/lnc.go, challenger/lnd.go, challenger/lnd_test.go, config.go, sample-conf.yaml
In this commit, we add a new CLI argument that allows a user to control if we use strict verification or not. Strict verification relies on checking the actual invoice state against lnd, and requires more state for the Aperture server.
When strict verification isn't on, we rely only on the preimage payment hash relationship. Namely that the only way a user can obtain the preimage is to pay the invoice, and as we check the HMAC on the macaroon, we know that we created it with an invoice obtained from lnd.
=> multi: add new strict-verify CLI option to control invoice usage

aperture.go, hashmail_server.go, hashmail_server_test.go, prometheus.go
This PR adds aggregation and classification of sessions into `{active, standby, inuse}` categories and makes direct metrics exportable.
It is an attempt to lower the cardinality of the prior used read count metric. This should greatly reduce the load on Prometheus for both storage and querying.
However, there is a caveat with the code as-is:
* Unbounded memory growth: while the prior approach essentially made it the prometheus server's problem, we now have to deal with this ourselves. Looking for feedback on an appropriate culling threshold. I wanted to first and foremost mimic what we were doing before so I did not implement culling yet.
=> aperture: internally aggregate session statistics to reduce cardinality

challenger/lnd.go
Seeing the following because `l.invoiceCancel()` isn't initialized when config `strictverify` isn't set.
```
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103fcf340]
goroutine 1 [running]:
github.com/lightninglabs/aperture/challenger.(*LndChallenger).Stop(0x140005fbc00)
/Users/bob/projects/go/src/github.com/aperture/challenger/lnd.go:273 +0x20
```
=> challanger: fix shutdown panic
